=== osca958/lenguajeDemarcas/Clase16XSD/ejemplo2/marcadores.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="marcadores">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="pagina" maxOccurs="unbounded"> <!--maxOccurs indica el mÃ¡ximo de repeticiones-->
                    <xs:complexType>
                        <xs:sequence> <!--si no importa el orden xs:all-->
                            <xs:element name="nombre" type="xs:string"/> 
                            <xs:element name="descripcion" type="xs:string"/>
                            <xs:choice>
                                <xs:element name="link" type="xs:string"/>
                                <xs:element name="url" type="xs:string"/>
                            </xs:choice>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== osca958/lenguajeDemarcas/Clase16XSD/ejemplo2/marcadores.xml
<?xml version="1.0" encoding="UTF-8"?>
<marcadores xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="marcadores.xsd">
    <pagina>
        <nombre>Abrilllave</nombre>
        <descripcion>Tutoriales para abrir llaves</descripcion>
        <url>https://www.abrirllave.com</url>
    </pagina>
    <pagina>
        <nombre>Wikipedia</nombre>
        <descripcion>la enciclopedia libre</descripcion>
        <url>https://www.wikipedia.org</url>
    </pagina>
    <pagina>
        <nombre>W3C</nombre>
        <descripcion>World Wide Web Consortium</descripcion>
        <link>https://www.w3.org</link>
    </pagina>

</marcadores>
